# use a docker image of ubuntu linux with gcc and mpich
# image: aglocer/ubuntu-mpich:v1

build:
  stage: build
  tags:
    - macbook 
  script:
    - ./Config.pl -install -compiler=gfortran
    - make -j test_compile
#  artifacts:
#    paths:
#      - mybinary
#      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  tags:
    - macbook 
  script:
    - ./Config.pl -install -compiler=gfortran
    - make -j test_compile
    - make test_rundir
    - make test_run
    - make test_check
    - ./check_empty_file.sh test_cimi.diff
