grid3_mpi-1.98.o:\
	param3_mpi-1.98.inc \
	com3_mpi-1.98.inc \
	/Users/aglocer/Research/CIMI/trunk/share/Library/src/ModMpi.o \
	ModSAMI.o

madala_sevp_dp.o:\
	param3_mpi-1.98.inc

sami3_mpi-1.98.o:\
	param3_mpi-1.98.inc \
	com3_mpi-1.98.inc \
	/Users/aglocer/Research/CIMI/trunk/share/Library/src/ModMpi.o \
	ModSAMI.o

